[P8-85] cleanup in lcgs examples and ebnf
d702e20/OnTheFlyATL pull request #119
Opened 2021-03-22 09:49 UTC by MathiasMehl

Removes the `public good game` and  `power control` lcgs programs
Moves the `mexican-standoff.json` into a directory called json-examples, next to lcgs-examples
Remove deprecated ebnf files, and updates the most updated one. 
Renames a bunch of lcgs files to use underscore instead of a hyphen

2021-03-22 11:42 UTC, cogitantium requested changes
This breaks benchmarking as you haven't updated the paths in `benchmark_solver.rs`.
Uncomment all relevant model-formula pairs in the 'static_thread_benches' group and do a `cargo bench` run to check if everything works.

Also there's still a lingering Mexican formula with 'survice', please rename that.

2021-03-24 07:43 UTC, NicEastvillage commented
I moved the grammars to https://github.com/d702e20/OnTheFlyATL/wiki/EBNF-for-ATL-and-LCGS and removed the docs folder.

2021-03-24 07:43 UTC, NicEastvillage approved these changes

2021-03-26 12:04 UTC, cogitantium approved these changes

2021-03-26 12:04 UTC, merged