Update ATL display to reflect ATL grammar
d702e20/OnTheFlyATL pull request #122
Opened 2021-03-23 08:52 UTC by NicEastvillage

Made ATL display and ATL grammar consistent by replacing the special characters with `<<`, `>>`, `[[`, `]]`, `F`, `G`, `X`.

2021-03-23 11:49 UTC, MathiasMehl commented on README.md
> +It uses an on-the-fly evaluation method as opposed to calculating the fixed point like PRISM do.
```suggestion
It uses an on-the-fly evaluation method as opposed to calculating the fixed point like PRISM does.
```

2021-03-23 11:51 UTC, MathiasMehl commented on README.md
> +This lazy method avoids having to generate the whole graph, and is therefore faster in most cases.
```suggestion
This lazy evaluation method avoids generating the whole graph, and is therefore faster in most cases.
```

2021-03-23 11:52 UTC, MathiasMehl commented on README.md
>  it's syntax is inspired by PRISM-lang, however, the concepts of syncronization and modules are very different.
```suggestion
its syntax is inspired by PRISM-lang, however, the concepts of synchronization and modules are very different.  
```

2021-03-23 12:02 UTC, MathiasMehl approved these changes

2021-03-30 07:50 UTC, cogitantium requested changes

2021-03-30 07:50 UTC, cogitantium commented on README.md
> +With this lazy method we avoid generating the whole graph, and it is therefore faster in most cases.
```suggestion
With this lazy method we avoid generating the whole graph, and it is therefore an order of magnitude faster in most cases.
```

We can link to SciHub/arXiv later on for this statement

2021-03-30 12:01 UTC, cogitantium approved these changes

2021-03-30 12:18 UTC, merged