P8_83 collecting of assignments
d702e20/OnTheFlyATL pull request #131
Opened 2021-03-30 07:17 UTC by lars4509

Collecting all assignments in the main thread for further use

2021-03-30 11:37 UTC, jenrik reviewed
I'm not entirely sure what this i good for. This will definitely become problematic when all workers no longer live in the same process (fx networked workers). Also the overhead of copying all the assignment to the main thread can become very expensive, try see if it instead can be moved.

2021-03-30 12:10 UTC, NicEastvillage requested changes

2021-03-30 12:10 UTC, NicEastvillage commented on atl-checker/src/edg.rs
> +        assignment_table.extend(assignments);
Extending the assignment table overrides values, but certain assignments needs to have priority, i.e. if one worker found a certain assignment, then that must be the one put into the table. Unknown < undecided < {true, false}.

2021-03-30 12:12 UTC, NicEastvillage commented
@jenrik we want to compute the partial strategy (a partial function from states to moves for each relevant player) that proves that the formula is true/false. We are still not entirely sure how to do this, but having the assignment is the first step.

2021-03-30 12:22 UTC, jenrik commented
I still uphold my concerns. I think you should delay this change until you know how to compute a partial strategy

2021-04-23 09:42 UTC, closed without merging

2021-04-23 09:44 UTC, NicEastvillage commented
Closing since it is so far behind main. I will resolve the conflicts and open PR, merging it to a development branch.