Additions to SymbolTable
d702e20/OnTheFlyATL pull request #17
Opened 2020-11-12 09:09 UTC by NicEastvillage

Refines the `SymbleTable` with more abstraction and better Symbols.

This PR is waiting for AST changes from #15

2020-11-18 12:07 UTC, cogitantium approved these changes
LGTM

2020-11-18 15:08 UTC, jenrik requested changes

2020-11-18 15:08 UTC, jenrik commented on src/lcgs/ast.rs
> +/// current state. Transitions in a CGS is the combination of all
```suggestion
/// current state. Transitions in a concurrent game structure is the combination of all
```

2020-11-18 15:30 UTC, NicEastvillage commented on src/lcgs/ast.rs
> +    /// The owner of the declaration, i.e. the name in from of the dot in "`p1.health`".
Spelling mistake. Should be ".. in front of the dot.."

2020-11-18 16:47 UTC, jenrik commented on src/lcgs/ast.rs
> +    /// The owner of the declaration, i.e. the name in from of the dot in "`p1.health`".
```suggestion
    /// The owner of the declaration, i.e. the name in front of the dot in "`p1.health`".
```

2020-11-19 00:15 UTC, jenrik approved these changes

2020-11-19 00:30 UTC, merged