Added distinctive queue for hyper edges and negation edges
d702e20/OnTheFlyATL pull request #36
Opened 2020-11-20 09:53 UTC by lars4509

Removed `select()` and instead added an ElseIf-chain, which exhaust the channels in this order: termination, message, hyper, negation.

The change is closer to fix #12, but the case where all workers is idle is still missing, but  since it is strongly related to #11, it is omitted for now.

2020-11-20 10:01 UTC, lars4509 commented
Hurtig note: Kom til at lave rollback på alt hvad jeg havde lavet over den sidste uge... men fixet det i dag og sørget for at commit mellem hver changes xD (oof)

2020-12-02 07:40 UTC, jenrik commented on src/com.rs
>  type WorkQueue<V> = Receiver<Message<V>>;
Seems like a good idea, it's just called that because it used to also contain hyper-edges and negation-edges

2020-12-02 09:33 UTC, NicEastvillage requested changes
Looks good. I am still not entirely sure how distances are update, but I assume you have tested that it works. I only found the few things.

2020-12-02 09:33 UTC, NicEastvillage commented on src/edg.rs
> +                                        self.counter = 0;
I think we should reset the counter whenever we do something that is not a negation edge too.

2020-12-02 09:33 UTC, NicEastvillage commented on src/edg.rs
> +                self.release_negations(max(self.unsafe_edges.len(), 0));
Unnecessary max

2020-12-02 09:56 UTC, jenrik requested changes
Look mostly good

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +        while self.unsafe_edges.len() >= dist && self.unsafe_edges.len() > 0 {
```suggestion
        while self.unsafe_edges.len() >= dist && !self.unsafe_edges.is_empty() {
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +    fn release_negations(&mut self, dist: usize) {
this function could use some clean up

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                    distance: self.distances.get(vertex).unwrap_or(&0).clone(),
Fixes `clippy` warning
```suggestion
                    distance: self.distances.get(vertex).unwrap_or(&0),
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +        let tdist = self.distances.get(vertex).unwrap_or(&default).clone();
Fixes `clippy` warning
```suggestion
        let tdist = self.distances.get(vertex).unwrap_or(&default);
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                let sdist = self.distances.get(&edge.source).unwrap_or(&default).clone() + 1;
Fixes `clippy` warning
```suggestion
                let sdist = self.distances.get(&edge.source).unwrap_or(&default) + 1;
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                let sdist = self.distances.get(&edge.source).unwrap_or(&default).clone();
Fixes `clippy` warning
```suggestion
                let sdist = self.distances.get(&edge.source).unwrap_or(&default);
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +            dependencies.insert(dependency.clone());
Fixes `clippy` warning
```suggestion
            dependencies.insert(dependency);
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +            dependencies.insert(dependency.clone());
Fixes `clippy` warning
```suggestion
            dependencies.insert(dependency);
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                self.explore(&edge.target, weight.clone());
the same weight is used twice. It should be `.split()` to avoid introducing extra into the system

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +            dist = n.clone();
Fixes `clippy` warning
```suggestion
            dist = *n;
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +            len = len + 1
Fixes `clippy` warning
```suggestion
            len += 1;
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +        while len <= dist as usize {
this might be better written as a for range loop

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                    self.distances
Clippy complains about illegal borrow

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                        .insert(vertex.clone(), max(dist.clone(), distance));
Fixes `clippy` warning
```suggestion
                        .insert(vertex.clone(), max(dist, distance));
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                    if let Some(dependencies) = self.depends.get(vertex) {
Is it a bug that `dependencies` isn't used or could this have been replaced with
```suggestion
                    if self.depends.contains_key(vertex) {
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +                            }
Fixes `clippy` warning
```suggestion
                            if let VertexAssignment::UNDECIDED = assignment {
                                self.explore(vertex, weight.clone());
                            }
```

2020-12-02 09:56 UTC, jenrik commented on src/edg.rs
> +        let changed_assignment = (prev_assignment != Some(assignment));
Fixes `clippy` warning
```suggestion
        let changed_assignment = prev_assignment != Some(assignment);
```

2020-12-02 14:29 UTC, NicEastvillage approved these changes

2020-12-03 14:38 UTC, jenrik requested changes
there are still `clippy` warnings that needs fixing. Also there is an illegal borrow that absolutely need a fix before we merge

2020-12-03 14:38 UTC, jenrik commented on src/edg.rs
> +                self.distances.insert(vertex.clone(), max(sdist, *tdist));
Please fix the `clippy` warning about an illegal borrow

2020-12-04 10:37 UTC, GeneralDenmark approved these changes
Looking good :tm:

2020-12-04 13:31 UTC, merged