[LCGS] Make IntermediateLCGS impl GameStructure
d702e20/OnTheFlyATL pull request #49
Opened 2020-11-25 13:58 UTC by NicEastvillage

Make `IntermediateLCGS` impl `GameStructure` and other improvements to run.

Depends on #44

2020-11-27 07:47 UTC, NicEastvillage commented
Asger's test helped me find an error. Expect one more commit to fix `state_from_index()`.

2020-11-27 10:04 UTC, cogitantium approved these changes
LGTN

2020-11-27 13:03 UTC, jenrik requested changes
I haven't fully understond `intermediate.rs` but it seem right.

Also there is `clippy` warnings that needs to be fixed.

2020-11-27 13:13 UTC, NicEastvillage commented on src/lcgs/ir/intermediate.rs
> +                    let size = var.ir_range.len() as i32;
I use i32 for runtime values. The u32 and usize comes from your representation of states, players, and labels in the algorithm.

2020-11-30 08:21 UTC, jenrik approved these changes

2020-11-30 08:26 UTC, merged