Cleans main.rs and fixes the "graph" subcommand
d702e20/OnTheFlyATL pull request #63
Opened 2020-12-02 20:27 UTC by jenrik

2020-12-02 21:46 UTC, NicEastvillage requested changes
Nice! This is much better. Only 8 lines of of dublicate code.

You might now be done with this PR from what I can tell, but here are some thoughts from me:
* This PR overshadows PR #58. Can you including infering of model type in this PR please?
* I would prefer if you wrote "Could not" or even better "Failed to" instead of "Couldn't" in the error messages.
* Comments are missing

2020-12-02 21:46 UTC, NicEastvillage commented on src/main.rs
> +            });
This error would be a parsing error. File IO errors are handled above.

2020-12-02 21:46 UTC, NicEastvillage commented on src/main.rs
> +            });
This error would be a semantics error. The user wrote something invalid.

2020-12-03 11:34 UTC, NicEastvillage approved these changes

2020-12-04 10:40 UTC, GeneralDenmark approved these changes
Looking Good :tm:

2020-12-06 03:30 UTC, merged