Remove [ignored] from working tests
d702e20/OnTheFlyATL pull request #93
Opened 2021-01-15 12:25 UTC by NicEastvillage

All of our tests now succeeds, so let's remove the [ignore] annotation so we can keep it that way.

2021-01-20 07:07 UTC, jenrik requested changes
Does not compile 👎 
There is some broken use statements referring to serde that should probably refer to the std library instead.

2021-01-20 08:15 UTC, NicEastvillage commented
I am aware. Somehow master compiles fine. But I fixed the serde import on the more important #92 PR

2021-02-15 12:28 UTC, cogitantium approved these changes

2021-02-17 23:17 UTC, jenrik approved these changes

2021-02-19 07:20 UTC, merged